# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
